### ISSUE TITLE
Could an update archive be provided?

### ISSUE THREAD

**Issue by ghost** [coderplus/m2e-connector-for-jaxws-maven-plugin#2]
Hi!

For anyone behind a heavy firewall/proxy, it's useful to be able to download a archive of the update site, to use for offline install. Could one possibly be provided? :)

For example, if you look at egit: https://www.eclipse.org/egit/download/ There is one available under the header 'EGit p2 repository ZIP download for system integrators:'.

Thanks! :)

**Comment by aneesh-joseph** [comment]
If you want a local copy of the repo, download a zip version of this GIT  repository, extract it and head to the docs directory in the archive. 


![image](https://user-images.githubusercontent.com/9010621/38915053-e609bb28-42ff-11e8-982c-c4801e09c89e.png)
