### ISSUE TITLE
Update Site Not Found

### ISSUE THREAD

**Issue by jmini** [coderplus/m2e-connector-for-jaxws-maven-plugin#3]
The P2 Update Site seems to be dead:
`http://coderplus.com/m2e-update-sites/jaxws-maven-plugin/`

I get this:
> ERROR: org.eclipse.equinox.p2.metadata.repository code=1000 No repository found at http://coderplus.com/m2e-update-sites/jaxws-maven-plugin/.
>  at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)

Or in a web browser:
> 404 Not Found
>
> The requested URL /m2e-update-sites/jaxws-maven-plugin/ was not found on this server.

**Comment by phreakadelle** [comment]
Same here

**Comment by ghost** [comment]
And here too, but since my last issue is still open after more then a year, I wouldn't hold your breath to it getting fixed.

**Comment by jmcshane** [comment]
I ended up building the plugin locally in order to get it installed.  The build did work and I was able to install the plugin

**Comment by chadwilliams06** [comment]
Plug in still not working, any one have a workaround besides building it locally?

**Comment by aneesh-joseph** [comment]
apologies for the very delayed response. Please use the update site @  https://coderplus.github.io/m2e-connector-for-jaxws-maven-plugin/

**Comment by jmini** [comment]
Thank you: I have opened #5 to update the read-me.
